// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCW46_Mp4ADl9QXcXGiYzIc0-nThuteao',
    appId: '1:499879109367:android:8bea4f4fc38ecb219d69f2',
    messagingSenderId: '499879109367',
    projectId: 'dreameen-dev',
    storageBucket: 'dreameen-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTPOqqTQcL1t4gjoyj9sHrDzAVYl3XGoA',
    appId: '1:499879109367:ios:6c0b66c27d46b92b9d69f2',
    messagingSenderId: '499879109367',
    projectId: 'dreameen-dev',
    storageBucket: 'dreameen-dev.appspot.com',
    iosClientId: '499879109367-ob2l5cp9cb4jr02uu5drjnvou6htbhk2.apps.googleusercontent.com',
    iosBundleId: 'com.fbstoragetest.firebasestoragetest',
  );
}
